PollApplication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('poll.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('list/', views.all_polls, name='all_polls'),
    path('create/', views.create_poll, name='create_poll'),
    path('result/<int:result_id>/', views.result, name='result'),
    path('vote/<int:vote_id>/', views.vote, name='vote'),
]

accounts/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models
from django.contrib.auth.models import User


class CreatePoll(models.Model):
    question = models.TextField()
    option_one = models.CharField(max_length=50)
    option_two = models.CharField(max_length=50)
    option_one_count = models.IntegerField(default=0)
    option_two_count = models.IntegerField(default=0)

    def __str__(self):
        return self.question

    def total(self):
        return self.option_one_count + self.option_two_count

PollApplication/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages


def register(request):
    if request.method == "POST":
        if request.POST['password'] == request.POST['confirm_password']:
            if User.objects.filter(username=request.POST['username']).exists():
                messages.info(request, "Username already taken")
                return redirect('register')
            elif User.objects.filter(email=request.POST['email']).exists():
                messages.info(request, "Email already taken")

            else:
                user = User.objects.create_user(username=request.POST['username'],
                                                email=request.POST['email'],
                                                first_name=request.POST['first_name'],
                                                last_name=request.POST['last_name'],
                                                password=request.POST['password'])
                user.save()
                messages.success(request, "User Created")
                return redirect('accounts:login')
        else:
            messages.info(request, "Password does not match")
            return redirect('accounts:register')
    return render(request, 'accounts/register.html')


def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('poll:all_polls')
        else:
            messages.info(request, "Invalid Credentials")
            return redirect('accounts:login')

    return render(request, 'accounts/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

poll/views.py
from django.shortcuts import render, redirect
from .models import CreatePoll
from django.contrib import messages
from django.http import HttpResponse


def all_polls(request):
    polls = CreatePoll.objects.all()
    context = {'polls': polls}
    return render(request, 'poll/all_polls.html', context)


def create_poll(request):
    if not request.user.is_authenticated:
        return render(request, 'accounts/login.html')
    else:
        if request.method == 'POST':
            if request.POST['question'] == '' or request.POST['option_one'] == '' or request.POST['option_two'] == '':
                messages.error(request, "Please fill all fields")
            else:
                poll = CreatePoll(question=request.POST['question'], option_one=request.POST['option_one'],
                                  option_two=request.POST['option_two'])
                poll.save()
                messages.success(request, 'New Poll Added')
                return redirect('poll:all_polls')
        return render(request, 'poll/create_poll.html')


def result(request, result_id):
    polls = CreatePoll.objects.get(pk=result_id)
    context = {'poll': polls}
    return render(request, 'poll/result.html', context)


def vote(request, vote_id):
    if not request.user.is_authenticated:
        return render(request, 'accounts/login.html')
    else:
        polls = CreatePoll.objects.get(pk=vote_id)
        if request.method == 'POST':
            selected_option = request.POST['polls']
            if selected_option == 'Option1':
                polls.option_one_count += 1
            elif selected_option == 'Option2':
                polls.option_two_count += 1
            else:
                return HttpResponse("Invalid")
            polls.save()
            return redirect('poll:result', polls.id)
        context = {'poll': polls}
        return render(request, 'poll/vote.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}

{% block css %}
.form-login {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.form-login .checkbox {
  font-weight: 400;
}
.form-login .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-login .form-control:focus {
  z-index: 2;
}
.form-login input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-login input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
{% endblock %}

{% block body %}
 <div class="container mt-5 text-center">
    <form class="form-login" method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="username" class="sr-only">Username</label>
      <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-outline-primary btn-block" type="submit">Sign in</button>
    </form>
    <p>Need an account? <a href="{% url 'accounts:register' %}">Register Here</a></p>
 </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %} Signup {% endblock %}

{% block css %}
.form-signup {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.form-signup .checkbox {
  font-weight: 400;
}
.form-signup .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signup .form-control:focus {
  z-index: 2;
}
.form-signup input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signup input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
{% endblock %}

{% block body %}
 <div class="container mt-5 text-center">
    <form class="form-signup" method="post" action="{% url 'accounts:register' %}">
      {% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
      <label for="username" class="sr-only">Username</label>
      <input type="text" id="username" name="username" class="form-control" placeholder="Username" required>
      <label for="f_name" class="sr-only">First Name</label>
      <input type="text" id="f_name" name="first_name" class="form-control" placeholder="First Name" required >
      <label for="l_name" class="sr-only">Last Name </label>
      <input type="text" id="l_name" name="last_name" class="form-control" placeholder="Last Name" required >
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
      <label for="inputPassword2" class="sr-only">Confirm Password</label>
      <input type="password" id="inputPassword2" name="confirm_password" class="form-control" placeholder="Confirm Password" required>
      <button class="btn btn-lg btn-outline-primary btn-block" type="submit">Signup</button>
    </form>
      <p>Already have an account? <a href="{% url 'accounts:login' %}">Login Here!</a></p>
 </div>
{% endblock %}

poll/templates/poll/all_polls.html
{% extends 'base.html' %}
{% block title %} All Polls {% endblock %}
{% block body %}
<div class="container">
    <div class="card text-center bg-grey mt-3">
        <h5 class="card-title">Available Polls</h5>
    </div>
</div>

{% for poll in polls %}
<div class="container mt-2 text-center">
    <div class="card">
        <div class="card-body">
            <p class="card-text">{{ poll.question }}</p>
            <a href="{% url 'poll:vote' poll.id %}" class="btn btn-outline-primary">Vote</a>
            <a href="{% url 'poll:result' poll.id %}" class="btn btn-outline-success">Result</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

poll/templates/poll/create_poll.html
{% extends 'base.html' %}
{% block title %} Add New Poll {% endblock %}
{% block body %}

<div class="container text-center">
    <div class="card text-center bg-grey mt-4">
        <h5 class="card-title">Create New Polls</h5>
    </div>
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
    <form method="post" action="{% url 'poll:create_poll' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="question">Create Question for Poll</label>
        <textarea class="form-control" name="question" id="question" rows="3"></textarea>
      </div>
      <div class="row">
        <div class="col-6">
            <div class="form-group">
              <label for="option">Option-1</label>
                <input type="text" class="form-control" name="option_one" id="option" placeholder="Enter Option One">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
              <label for="option_">Option-2</label>
                <input type="text" class="form-control" name="option_two" id="option_" placeholder="Enter Option two">
            </div>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>
  </div>

{% endblock %}

poll/templates/poll/result.html
{% extends 'base.html' %}
{% block title %} Results {% endblock %}
{% block body %}
<div class="container text-center">
    <div class="card-body">
        <h3>Poll Result</h3>
    </div>
    <div class="card">
        <h2>{{ poll.question }}</h2>
    </div>
    <ul class="list-group">
        <li class="list-group-item">{{ poll.option_one }} &mdash; <strong>{{ poll.option_one_count }}</strong></li>
        <li class="list-group-item">{{ poll.option_two }} &mdash; <strong>{{ poll.option_two_count }}</strong></li>
    </ul>
    <div class="footer">
        Total &mdash; <strong>{{ poll.total }}</strong>
    </div>
</div>
{% endblock %}

poll/templates/poll/vote.html
{% extends 'base.html' %}
{% block title %} Vote {% endblock %}
{% block body %}
<div class="container text-center">
<div class="row">
    <div class="col">
        <div class="card-body">
            <h3>Choose Your Vote</h3>
        </div>
        <div class="card">
            <div class="row">
                <div class="col">
                    <h2>{{ poll.question }}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <hr />
                    <form method="post" action="{% url 'poll:vote' poll.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="polls" value="Option1" required>
                                    {{ poll.option_one }}
                                </label> &nbsp;
                                <label>
                                    <input type="radio" name="polls" value="Option2" required>
                                    {{ poll.option_two}}
                                </label> &nbsp;
                            </div>
                        </div>
                        <button type="submit" class="btn btn-outline-primary btn-sm">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}Poll Application{% endblock %}</title>
    <style>
      {% block css %} {% endblock %}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark py-1 bg-dark">
      <a class="navbar-brand" href="/">Poll Application</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'poll:all_polls' %}">Polls</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'poll:create_poll' %}">Create Poll</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link">{{ user.first_name }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              {% else %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Sign in</a>
            </li>
            {% endif %}
          </ul>
      </div>
    </nav>
    {% block body %} {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Poll Application {% endblock %}
{% block body %}
<div class="jumbotron text-center" style="height: 690px; background-color:#4b5e5e;">
  <h1 class="display-4 mt-5">Poll Application</h1>
  <p class="lead mt-5">You can help us by voting.</p>
  <p class="mt-2">You can vote here.</p>
  <p class="lead mt-5">
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %}" role="button">Sign in</a>
    <a class="btn btn-primary btn-lg" href="{% url 'poll:all_polls' %}" role="button">All Available Poll</a>
  </p>
</div>
{% endblock %}